### ISSUE TITLE
KeyError in get_representative_docs() in v0.9

### ISSUE THREAD

**Issue by zynos** [MaartenGr/BERTopic#190]
I have 7 topics and one is missing if i call the `get_representative_docs()` with "5" as an argument
The reason is that in the `_map_representative_docs()` the variable `updated_representative_docs` is missing "5" as a key.
The "5" key is missing because with self.mapped_topics  only the "-1" is mapped to 5. 
See screenshot
![BerTopicBug](https://user-images.githubusercontent.com/8973150/127447849-95ad554d-bcce-49ad-b9e8-66c5f517859e.PNG)

**Comment by MaartenGr** [comment]
Hmmm, that is likely a result of either issues when reducing, or, which is more likely, the fact that I do not include representative documents for the cluster -1 since those are outliers:

https://github.com/MaartenGr/BERTopic/blob/01542ac4aa05177d9fb23dd7d11c95a225744fdc/bertopic/_bertopic.py#L1464-L1476

I could create a fix for this by adding -1 to the representative docs by keeping it empty. 

However, this issue should only appear if you have too few topics for the model. 7 or so topics is way too low and indicates that you either need more data or lower `min_topic_size`.

**Comment by zynos** [comment]
The `_update_topic_size()` function gets called multiple times.
At the beginning the biggest cluster is cluster 1.
After `_sort_mappings_by_frequency()` is called the biggest cluster is -1

See screenshot debugging before and after
`self.topic_sizes = dict(zip(sizes.Topic, sizes.Document))`
![BerTopicBug2](https://user-images.githubusercontent.com/8973150/127456721-941a8ba8-5d8d-4397-9d99-57f3b87aec09.PNG)

**Comment by MaartenGr** [comment]
Yes, that seems to be an issue with having too little topics. If there are a sufficient amount of topics, then the outlier topic will always be the largest and set to -1. Here, it seems you overfitted on the number of topics (by either setting them too low, having too little topics, or perhaps setting `min_topic_size` too high) which results in a very low number of topics. 

Could you share your initialization procedure of BERTopic? I believe that is where you most likely will find the cause.

**Comment by zynos** [comment]
I think that the problem is that `self.topic_sizes` influences `self.mapped_topics` here: 
```
sorted_topics = {topic: index - 1 for index, topic
                         in enumerate(self.topic_sizes.keys())}
self.mapped_topics = {og_topic: sorted_topics[topic]
                      if topic in sorted_topics
                      else topic
                      for og_topic, topic in self.mapped_topics.items()}
  ```
  and `self.mapped_topics` directly influences `representative_docs` here
  ```
for old_topic, docs in representative_docs.items():
    new_topic = self.mapped_topics[old_topic]
    updated_representative_docs[new_topic] = docs

self.representative_docs = updated_representative_docs       
        
  ```
  
  
  Regarding initialization, it is vanilla:
```
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(abstracts)
```

But why do you set the largest cluster to -1 if the cluster algorithm does not predict an outlier label for it?

**Comment by zynos** [comment]
The dataset is also really small ( less then 3K samples)

**Comment by MaartenGr** [comment]
The main issue then lies here: 

```python
sorted_topics = {topic: index - 1 for index, topic
                         in enumerate(self.topic_sizes.keys())}
```

Which assumes that the largest cluster is -1, which is always the case unless the model could not be trained with enough data as is the case with your dataset. Correcting this requires a bit more code than I would like but I'll see if I can manage something simple/elegant. 

Thanks for debugging this though, definitely helps out identifying the issue.

**Comment by zynos** [comment]
No problem, thank you for your work and your fast replys so far!
Maybe the assumption, that the biggest cluster is always the outlier (-1) is false for smaller datasets but maybe it is also false for some bigger datasets?

**Comment by MaartenGr** [comment]
Although it is theoretically possible, in practice data is almost never so clean that there is a larger cluster than outliers seeing as HDBSCAN is rather strict when it comes to that. 

Also, I just pushed a commit that should fix this issue. Could you try it out and see what happens?

**Comment by zynos** [comment]
Now the biggest cluster is mapped to 0 instead of -1.
I removed the names
```
 Topic  Count                                     Name
0      0   1772                       0_
1      1    234   1_
2      2    186              2_
3      3    170                    3_
4      4     46                   4_
5      5     40               5_
6      6     36               6_
7     -1     25      -1_
8      7     19            7_
```

**Comment by MaartenGr** [comment]
Yes, that is on purpose. -1 refers to the outlier class and should generally not be regarded. So the actual counting of topics starts at 0.

**Comment by zynos** [comment]
The index error is resolved by this fix, thanks alot! Hope v0.9 is soon merged :D

**Comment by zecknos** [comment]
Hi @MaartenGr ,

I am using v0.9.1, and I am still getting the 
**KeyError: -1**

I am running with default params, on 500 documents with number of topics = 5.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/85686306/132511235-bdded77b-c56a-4e14-86bc-f8f28fa7d07e.png">

**Comment by MaartenGr** [comment]
There might be an issue with the number of topics you generated. I would advise with a small number of documents to not use `nr_topics`. Also, 500 documents is a really low value for representing topics. It typically works best with an order of several thousand documents. Finally, reducing `min_topic_size` might increase the number of generated topics.

**Comment by zecknos** [comment]
Thanks @MaartenGr for the prompt response.
